# Generated by Django 4.2.6 on 2023-11-08 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=150)),
                ('slug', models.SlugField(default='', max_length=150)),
                ('sottotitolo', models.CharField(max_length=255)),
                ('contenuto', models.TextField(default='')),
                ('img', models.ImageField(blank=True, default='img_slide/no-image.png', null=True, upload_to='img_slide/', verbose_name='Immagine da visualizzare')),
                ('data_inserimento', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
