# Generated by Django 4.2.6 on 2023-11-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('descrizione', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='slide',
            name='img_visibile',
            field=models.BooleanField(default=False, verbose_name='Pubblicata'),
        ),
        migrations.AddField(
            model_name='slide',
            name='categoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.categoriaslide'),
        ),
    ]
