# Generated by Django 4.2.6 on 2023-11-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_categoriaslide_slide_img_visibile_slide_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='categoria',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.categoriaslide'),
        ),
    ]
