# Generated by Django 4.2.6 on 2023-11-10 16:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_slide_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='contenuto',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
