# Generated by Django 4.2.6 on 2023-11-16 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_cap_userprofile_comune_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cap',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Inserisci un cap corretto.', regex='[0-9]{5}')]),
        ),
    ]
