# Generated by Django 4.2.6 on 2023-11-13 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('img', models.ImageField(default='img_prodotti/no-image.jpg', upload_to='img_prodotti/%Y/%m/%d/')),
                ('descrizione', models.TextField(blank=True)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantita', models.IntegerField(default=0, verbose_name='Quantità in magazzino')),
                ('pubblicato', models.BooleanField(default=False)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti', to='shop.categoria')),
            ],
            options={
                'verbose_name': 'prodotto',
                'verbose_name_plural': 'prodotti',
                'ordering': ['nome'],
            },
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nome'], name='shop_catego_nome_43d445_idx'),
        ),
        migrations.AddIndex(
            model_name='prodotto',
            index=models.Index(fields=['id', 'slug'], name='shop_prodot_id_13f4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='prodotto',
            index=models.Index(fields=['nome'], name='shop_prodot_nome_9f430a_idx'),
        ),
        migrations.AddIndex(
            model_name='prodotto',
            index=models.Index(fields=['-data_inserimento'], name='shop_prodot_data_in_59736f_idx'),
        ),
    ]
