# Generated by Django 4.2.6 on 2023-11-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_categoria_categoriaprincipale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoriaPrincipale',
            new_name='categoria_principale',
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('slug', 'categoria_principale')},
        ),
    ]
